-- Fat Fish: initial schema (players, installations, runs, run_items)

CREATE TABLE players (
    id           UUID PRIMARY KEY,
    display_name VARCHAR(60),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- An installation stays anonymous (player_id NULL) until it is linked to a player.
CREATE TABLE installations (
    id         UUID PRIMARY KEY,
    player_id  UUID REFERENCES players (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_installations_player_id ON installations (player_id);

-- run_id is generated by the game, which makes the batch upload idempotent.
CREATE TABLE runs (
    run_id              UUID PRIMARY KEY,
    installation_id     UUID        NOT NULL REFERENCES installations (id),
    player_id           UUID REFERENCES players (id),
    schema_version      INTEGER     NOT NULL,
    game_version        VARCHAR(20) NOT NULL,
    started_at          TIMESTAMPTZ NOT NULL,
    ended_at            TIMESTAMPTZ NOT NULL,
    result              VARCHAR(20) NOT NULL,
    level_reached       INTEGER     NOT NULL,
    rounds_cleared      INTEGER     NOT NULL,
    bosses_defeated     INTEGER     NOT NULL,
    max_spin_score      BIGINT      NOT NULL,
    total_spins         INTEGER     NOT NULL,
    total_bet           BIGINT      NOT NULL,
    total_won           BIGINT      NOT NULL,
    total_lost          BIGINT      NOT NULL,
    all_in_count        INTEGER     NOT NULL,
    pawned_assets       JSONB       NOT NULL DEFAULT '[]'::jsonb,
    loans_taken         INTEGER     NOT NULL,
    loan_total          BIGINT      NOT NULL,
    most_desperate_spin JSONB,
    received_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_runs_result CHECK (result IN ('defeat', 'demo_victory', 'abandoned')),
    CONSTRAINT chk_runs_level CHECK (level_reached BETWEEN 1 AND 3),
    CONSTRAINT chk_runs_dates CHECK (ended_at > started_at),
    CONSTRAINT chk_runs_non_negative CHECK (
        rounds_cleared >= 0 AND bosses_defeated >= 0 AND max_spin_score >= 0
        AND total_spins >= 0 AND total_bet >= 0 AND total_won >= 0 AND total_lost >= 0
        AND all_in_count >= 0 AND loans_taken >= 0 AND loan_total >= 0
    )
);

CREATE INDEX idx_runs_player_started ON runs (player_id, started_at DESC);
CREATE INDEX idx_runs_installation_id ON runs (installation_id);

CREATE TABLE run_items (
    run_id    UUID        NOT NULL REFERENCES runs (run_id) ON DELETE CASCADE,
    position  INTEGER     NOT NULL,
    item_code VARCHAR(50) NOT NULL,
    PRIMARY KEY (run_id, position)
);
